# Generated by Django 5.1.2 on 2024-10-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.CharField(choices=[('C', 'Chain Replacement'), ('T', 'Tire Replacement'), ('W', 'Wax Chain'), ('B', 'Brake Check')], default='C', max_length=1),
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('bike', models.ManyToManyField(related_name='upgrades', to='my_app.bike')),
            ],
        ),
    ]
