# Generated by Django 5.1.2 on 2024-10-30 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_maintenance_maintenance_type_upgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upgrade',
            name='type',
        ),
        migrations.AddField(
            model_name='upgrade',
            name='date_installed',
            field=models.DateField(blank=True, null=True, verbose_name='Installation Date'),
        ),
        migrations.RemoveField(
            model_name='upgrade',
            name='bike',
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='upgrade',
            name='bike',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.bike'),
        ),
    ]
