# Generated by Django 5.1.2 on 2024-10-30 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_remove_upgrade_type_upgrade_date_installed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgrade',
            name='type',
            field=models.CharField(default='Standard', max_length=100),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.bike'),
        ),
        migrations.AlterField(
            model_name='upgrade',
            name='date_installed',
            field=models.DateField(default='2023-1-1'),
            preserve_default=False,
        ),
    ]
